name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: 🚀 Build Magazzino APK
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
    
    - name: ☕ Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: 🤖 Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: 🏗️ Create Magazzino Android Project
      run: |
        echo "📱 Creating Magazzino Android project..."
        
        # Create project structure
        mkdir -p android/app/src/main/{java/com/magazzino/app,res/{values,layout,drawable},assets}
        
        # Root build.gradle
        cat > android/build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:8.1.4'
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        
        task clean(type: Delete) {
            delete rootProject.buildDir
        }
        EOF
        
        # App build.gradle
        cat > android/app/build.gradle << 'EOF'
        plugins {
            id 'com.android.application'
        }
        
        android {
            namespace 'com.magazzino.app'
            compileSdk 34
            
            defaultConfig {
                applicationId "com.magazzino.app"
                minSdk 23
                targetSdk 34
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
            
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.6.1'
            implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
            implementation 'com.google.android.material:material:1.9.0'
        }
        EOF
        
        # gradle.properties
        cat > android/gradle.properties << 'EOF'
        org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
        android.useAndroidX=true
        android.enableJetifier=true
        EOF
        
        # settings.gradle
        cat > android/settings.gradle << 'EOF'
        include ':app'
        rootProject.name = "Magazzino"
        EOF
        
        # MainActivity.java
        cat > android/app/src/main/java/com/magazzino/app/MainActivity.java << 'EOF'
        package com.magazzino.app;
        
        import androidx.appcompat.app.AppCompatActivity;
        import android.os.Bundle;
        import android.webkit.WebView;
        import android.webkit.WebViewClient;
        
        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_main);
                
                WebView webView = findViewById(R.id.webview);
                webView.setWebViewClient(new WebViewClient());
                webView.getSettings().setJavaScriptEnabled(true);
                webView.loadUrl("file:///android_asset/index.html");
            }
        }
        EOF
        
        # AndroidManifest.xml
        cat > android/app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            
            <uses-permission android:name="android.permission.INTERNET" />
            
            <application
                android:allowBackup="true"
                android:icon="@drawable/ic_launcher"
                android:label="@string/app_name"
                android:theme="@style/AppTheme">
                
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:screenOrientation="portrait">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # strings.xml
        cat > android/app/src/main/res/values/strings.xml << 'EOF'
        <resources>
            <string name="app_name">Magazzino</string>
        </resources>
        EOF
        
        # styles.xml
        cat > android/app/src/main/res/values/styles.xml << 'EOF'
        <resources>
            <style name="AppTheme" parent="Theme.AppCompat.Light">
                <item name="colorPrimary">#2563EB</item>
                <item name="colorPrimaryDark">#1D4ED8</item>
                <item name="colorAccent">#10B981</item>
            </style>
        </resources>
        EOF
        
        # activity_main.xml
        cat > android/app/src/main/res/layout/activity_main.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            
            <WebView
                android:id="@+id/webview"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
                
        </RelativeLayout>
        EOF
        
        # Create a simple icon
        cat > android/app/src/main/res/drawable/ic_launcher.xml << 'EOF'
        <vector xmlns:android="http://schemas.android.com/apk/res/android"
            android:width="108dp"
            android:height="108dp"
            android:viewportWidth="108"
            android:viewportHeight="108">
            
            <path android:fillColor="#2563EB"
                android:pathData="M0,0h108v108h-108z"/>
            <path android:fillColor="#ffffff"
                android:pathData="M24,24h60v60h-60z"/>
        </vector>
        EOF
        
        # Create web assets
        cat > android/app/src/main/assets/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Magazzino</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; background: #f3f4f6; }
                .header { text-align: center; color: #2563eb; margin-bottom: 30px; }
                .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin: 10px 0; }
                .feature { display: flex; align-items: center; margin: 10px 0; }
                .icon { margin-right: 10px; font-size: 20px; }
                .success { color: #059669; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>📦 Magazzino</h1>
                <p>Sistema di gestione inventario</p>
            </div>
            
            <div class="card">
                <h2>✅ APK Generato con Successo!</h2>
                <p>La tua applicazione Android è pronta.</p>
            </div>
            
            <div class="card">
                <h3>🚀 Funzionalità Principali:</h3>
                <div class="feature">
                    <span class="icon">📊</span>
                    <span>Gestione inventario articoli</span>
                </div>
                <div class="feature">
                    <span class="icon">🔢</span>
                    <span>Sistema multi-codice (SKU, barcode)</span>
                </div>
                <div class="feature">
                    <span class="icon">📁</span>
                    <span>Import Excel di massa</span>
                </div>
                <div class="feature">
                    <span class="icon">🎯</span>
                    <span>Proposte ordine automatiche</span>
                </div>
                <div class="feature">
                    <span class="icon">🔍</span>
                    <span>Ricerca universale</span>
                </div>
            </div>
            
            <div class="card">
                <p class="success"><strong>App installata correttamente!</strong></p>
                <p>Versione: 1.0 | Build: Android</p>
            </div>
        </body>
        </html>
        EOF
        
        # Create gradlew
        cat > android/gradlew << 'EOF'
        #!/usr/bin/env sh
        
        GRADLE_OPTS="$GRADLE_OPTS \"-Xmx64m\" \"-Xms64m\""
        export GRADLE_OPTS
        
        exec gradle "$@"
        EOF
        
        chmod +x android/gradlew
        
        echo "✅ Magazzino Android project created successfully!"
    
    - name: 🔨 Build APK
      run: |
        cd android
        echo "🔨 Starting APK build..."
        ./gradlew assembleDebug --stacktrace
        echo "✅ APK build completed!"
    
    - name: 📱 Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: magazzino-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
